### ISSUE TITLE
File requirements_test.txt doesn't exist

### ISSUE THREAD

**Issue by jeffarrubla** [anexia-it/django-rest-passwordreset#112]
Would you mind to share the contents of the file **requirements_test.txt** to run the tests please?
Thanks in advance

**Comment by ChristianKreuzberger** [comment]
The file has been removed in #111 by @anx-cbenke. Version 1.0.0 still had this, but it seems to have been removed ever since.

https://github.com/anexia-it/django-rest-passwordreset/blob/1.0.0/requirements_test.txt

However, I don't think this file is still needed for running tests.

@anx-cbenke there is still a reference in [README.md stating how tests should be executed](https://github.com/anexia-it/django-rest-passwordreset/blob/master/README.md#tests), maybe this can be updated?

**Comment by anx-cbenke** [comment]
Correct! Thanks for the hint, fixed in #114
